In [1]:
import os
import numpy as np
import pandas as pd

In [4]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

In [5]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
sub_train['WEEKDAY_APPR_PROCESS_START'] = labelencoder.fit_transform(sub_train['WEEKDAY_APPR_PROCESS_START'])
sub_train

        WEEKDAY_APPR_PROCESS_START
0                                6
1                                1
2                                1
3                                6
4                                4
...                            ...
307506                           4
307507                           1
307508                           4
307509                           6
307510                           4

[307511 rows x 1 columns]

In [8]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
sub_train_ohe=onehotencoder.fit_transform(sub_train).toarray()
pd.DataFrame(sub_train_ohe)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

          0    1    2    3    4    5    6
0       0.0  0.0  0.0  0.0  0.0  0.0  1.0
1       0.0  1.0  0.0  0.0  0.0  0.0  0.0
2       0.0  1.0  0.0  0.0  0.0  0.0  0.0
3       0.0  0.0  0.0  0.0  0.0  0.0  1.0
4       0.0  0.0  0.0  0.0  1.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
307506  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307507  0.0  1.0  0.0  0.0  0.0  0.0  0.0
307508  0.0  0.0  0.0  0.0  1.0  0.0  0.0
307509  0.0  0.0  0.0  0.0  0.0  0.0  1.0
307510  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[307511 rows x 7 columns]